from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ShortcutsWindow(object):
    def setupUi(self, ShortcutsWindow):
        ShortcutsWindow.setObjectName("ShortcutsWindow")
        ShortcutsWindow.setFixedSize(QtCore.QSize(399, 292))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./assets/img/icons8-camera-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ShortcutsWindow.setWindowIcon(icon)
        self.tableView = QtWidgets.QTableView(ShortcutsWindow)
        self.tableView.setGeometry(QtCore.QRect(0, 0, 401, 291))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setObjectName("tableView")
        self.tableWidget = QtWidgets.QTableWidget(ShortcutsWindow)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 401, 291))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMaximumSize(QtCore.QSize(401, 411))
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Shortcuts")
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(True)
        self.tableWidget.verticalHeader().setStretchLastSection(True)

        self.retranslateUi(ShortcutsWindow)
        QtCore.QMetaObject.connectSlotsByName(ShortcutsWindow)

    def retranslateUi(self, ShortcutsWindow):
        _translate = QtCore.QCoreApplication.translate
        ShortcutsWindow.setWindowTitle(_translate("ShortcutsWindow", "Shortcuts"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("ShortcutsWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("ShortcutsWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("ShortcutsWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("ShortcutsWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("ShortcutsWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("ShortcutsWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("ShortcutsWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("ShortcutsWindow", "8"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ShortcutsWindow", "Key Combinations"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("ShortcutsWindow", "Open About"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("ShortcutsWindow", "Ctrl+Shift+A"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("ShortcutsWindow", "Check Shortcuts"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("ShortcutsWindow", "Ctrl+Shift+S"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("ShortcutsWindow", "Open Browse Images"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("ShortcutsWindow", "Ctrl+B"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("ShortcutsWindow", "Close"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("ShortcutsWindow", "Ctrl+X"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("ShortcutsWindow", "Help"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("ShortcutsWindow", "Ctrl+H"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("ShortcutsWindow", "Cancel"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("ShortcutsWindow", "Ctrl+Shift+X"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("ShortcutsWindow", "Process"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("ShortcutsWindow", "Ctrl+P"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("ShortcutsWindow", "Quit OpenCV Window"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("ShortcutsWindow", "Q"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)

